### ISSUE TITLE
NOW IS READY FOR REVIEW

### ISSUE THREAD

**Issue by ldiazre** [ldiazre/decont#2]

**Comment by tdido** [comment]
Esto está fenomenal, Laura. Pasando del stress el lunes a añadir opciones que ni fueron explicadas ;)

El único comentario, por decirte algo, es que estás la segunda mención al directorio y archivo de los wget no es necesaria: basta con `wget -i data/urls -P data`. Esto no impacta tu solución, es simplemente para que lo tengas en cuenta en el futuro.

**Comment by ldiazre** [comment]
Hola Tomás, muchísimas gracias
La opción (aunque supongo que ya lo sabes), es para que no se descargue el archivo. Ya que como tenía este comando incoporado, lo vi más util que añadir el _if_ como en los demás puntos, y así conseguir que el segundo bonus se aplicara a todo el script.
Aunque dijiste que no importaba, subí los scripts el martes y los bonus el miércoles. Pero olvidé que también tenía que asignarte las issues, por eso no te apareció hasta ayer, no sé si eso afecta, pero para que lo supieras.

**Comment by tdido** [comment]
Sí tenés razón, me equivoqué, el comando sería `wget -i data/urls -P data -nc`, pero sin el directorio que le ponías al final. A eso me refería,
